apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: test
spec: 
  replicas: 2 # tells deployment to run 2 pods matching the template 
  selector: 
    matchLabels: 
      app: test
  template:
    metadata: 
      labels: 
        run: test 
    spec: 
      containers: 
      - name: test 
        image: houssemdocker/angular-app:819
        ports: 
        - containerPort: 80 
